/*  core.h - Core libhak engine.
    
    Copyright 2013  Francisco Jose Monaco   <monaco.fj@gmail.com>

    This file is part of Libhak. 

    Libhak is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Libhak is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with .  If not, see <http://www.gnu.org/licenses/>. 

*/

#ifndef _HAK_CORE_H
#define _HAK_CORE_H

#include <stdio.h>
#include <stdlib.h>
#include <config.h>

/* Libhak engine. */

typedef struct hak_engine_t hak_engine_t;
struct hak_engine_t
{
  int error;		        /* Error code generated by the last functional call. */
  char *program_name;		/* Program invocation short name. */
  int argc;			/* Number of command line arguments. */
  char **argv;			/* Pointer to the command line arguments. */
  FILE *logstream;		/* Where to log messages. */
  char *symbol_log;		/* Log symbol. */
  char *symbol_sysfault;	/* Sysfault log symbol. */
  char *symbol_verify;		/* Verify log symbol. */
  char *symbol_assert;		/* Assert log symbol. */
};

extern hak_engine_t hak_engine;

/* Useful macros. */

#define HAK_TRUE  1
#define HAK_FALSE 0

/* Show basic libhak information. */

void hak_info(void);

/* Initialize libhak engine.  */

int hak_initialize (int, char **);


#endif	/* _HAK_CORE_H */
