/*  messages.c - Messages generated by libhak.
    
    Copyright 2013  Francisco Jose Monaco   <monaco.fj@gmail.com>

    This file is part of Libhak. 

    Libhak is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Libhak is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with .  If not, see <http://www.gnu.org/licenses/>. 

*/

#include <config.h>
#include <libhak.h>
#include <stdarg.h>

/* TODO: gettextize libhak messages. */


/* Error messages for hak_engine.error. */


const char *hak_error_messages[] =
  {
    "Success",			/* hak_verify_ok. */
    "Unspecified fault",        /* hak_verify_fault. (generic) */
  };

/* Log symbols */

const char* hak_symbols[] = 
  {
    "Log: ",
    "System: ",
    "Verify :",
    "Assert :",
    "Check: "
  };

/* Program Log (prepend program name)*/

int hak_log (const char *format, ...)
{
  va_list ap;
  int n;
  va_start (ap, format);
  n = fprintf (hak_engine.logstream, "%s", hak_engine.symbol_log);
  n = vfprintf (hak_engine.logstream, format, ap);
  return n;
}


